-- Agregar registros de CONTINENTE 
INSERT INTO Continente(Id, Nombre) VALUES( 1,'AMERICA');
INSERT INTO Continente(Id, Nombre) VALUES( 2,'EUROPA');
INSERT INTO Continente(Id, Nombre) VALUES( 3,'AFRICA');
INSERT INTO Continente(Id, Nombre) VALUES( 4,'ASIA');
INSERT INTO Continente(Id, Nombre) VALUES( 5,'OCEANIA');

-- Agregar registros de TIPOREGION 
INSERT INTO TipoRegion(Id, TipoRegion) VALUES( 1,'ESTADO');
INSERT INTO TipoRegion(Id, TipoRegion) VALUES( 2,'PROVINCIA');
INSERT INTO TipoRegion(Id, TipoRegion) VALUES( 3,'DEPARTAMENTO');


-- Agregar registros de PAIS 
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 1,'COLOMBIA', 1, 3,'PESO COLOMBIANO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 2,'ARGENTINA', 1, 1,'PESO ARGENTINO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 3,'BOLIVIA', 1, 1,'PESO BOLIVIANO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 4,'BRASIL', 1, 1,'REAL');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 5,'CANADA', 1, 1,'DOLAR CANADIENSE');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 6,'COSTA RICA', 1, 1,'COLON');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 7,'REPUBLICA DOMINICANA', 1, 1,'PESO DOMINICANO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 8,'CUBA', 1, 1,'DOLAR');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES( 9,'CHILE', 1, 1,'PESO CHILENO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(10,'ECUADOR', 1, 1,'DOLAR');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(11,'ESTADOS UNIDOS DE AMÉRICA', 1, 1,'DOLAR');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(12,'GUATEMALA', 1, 1,'QUETZAL');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(13,'HONDURAS', 1, 1,'PESO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(14,'MÉXICO', 1, 1,'PESO MEXICANO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(15,'NICARAGUA', 1, 1,'PESO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(16,'PANAMA', 1, 1,'BALBOA');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(17,'PARAGUAY', 1, 1,'GUARANI');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(18,'PERU', 1, 1,'NUEVO SOL');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(19,'URUGUAY', 1, 1,'PESO URUGUAYO');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(20,'VENEZUELA', 1, 1,'NUEVO BOLIVAR');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(21,'REINO UNIDO', 2, 1,'LIBRA ');
INSERT INTO Pais (Id, Nombre, IdContinente, IdTipoRegion, Moneda) VALUES(22,'ESPAÑA', 2, 1,'EURO');
INSERT INTO PAIS (Id, Nombre, IdCOntinente, IdTipoRegion, Moneda) VALUES(23,'ITALIA', 3, 1,'EURO');
INSERT INTO PAIS (Id, Nombre, IdCOntinente, IdTipoRegion, Moneda) VALUES(24,'FRANCIA', 3, 1,'EURO');
INSERT INTO PAIS (Id, Nombre, IdCOntinente, IdTipoRegion, Moneda) VALUES(25,'AUSTRALIA', 5, 1, 'DOLAR AUSTRALIANO');


-- Agregar registros de REGION 
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(107,'Morelos',14,      4892,   1605000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(108,'Nayarit',14,     27862,    943000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(109,'Nuevo Leon',14,     64203,   4164000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(110,'Oaxaca',14,     93343,   3522000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(111,'Puebla',14,     34251,   5391000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(112,'Queretaro',14,     11658,   1593000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(113,'Quintana Roo',14,     42535,   1134000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(114,'San Luis Potosi',14,     61165,   2412000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(115,'Sinaloa',14,     57331,   2610000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(116,'Sonora',14,    184946,   2384000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(117,'Tabasco',14,     24747,   2013000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(118,'Tamaulipas',14,     80148,   3020000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(119,'Tlaxcala',14,      3997,   1061000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(120,'Veracruz',14,     71856,   7081000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(121,'Yucatan',14,     39671,   1803000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(122,'Zacatecas',14,     75416,   1357000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(123,'Distrito Federal',14,         0,   8670000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(124,'Acre', 4,         0,    557526);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(125,'Alagoas', 4,         0,   2822621);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(126,'Amapa', 4,         0,    477032);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(127,'Amazonas', 4,         0,   2812557);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(128,'Bahia', 4,         0,  13070250);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(129,'Ceara', 4,         0,   7430661);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(130,'Distrito Federal', 4,         0,   2051146);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(131,'Espirito Santo', 4,         0,   3097232);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(132,'Goias', 4,         0,   5003228);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(133,'Maranhão', 4,         0,   5651475);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(134,'Mato Grosso', 4,         0,   2504353);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(135,'Mato Grosso do Sul', 4,         0,   2078001);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(136,'Minas Gerais', 4,         0,  17891494);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(137,'Para', 4,         0,   6192307);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(138,'Paraiba', 4,         0,   3443825);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(139,'Parana', 4,         0,   9563458);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(140,'Pernambuco', 4,         0,   7918344);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(141,'Piaui', 4,         0,   2843278);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(142,'Rio de Janeiro', 4,         0,  14391282);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(143,'Rio Grande do Norte', 4,         0,   2776782);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(144,'Rio Grande do Sul', 4,         0,  10187798);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(145,'Rondonia', 4,         0,   1379787);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(146,'Roraima', 4,         0,    324397);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(147,'Santa Catarina', 4,         0,   5356360);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(148,'Sao Paulo', 4,         0,  37032403);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(149,'Sergipe', 4,         0,   1784475);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(150,'Tocantins', 4,         0,   1157098);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(151,'Distrito Autonomo', 2,         0,   3000000);
INSERT INTO Region (Id, Nombre, IdPais, Area, Poblacion) VALUES(152,'Beni', 3,         0,         0);

-- Agregar registros de CIUDAD 
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1104,'Parana',  38,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1105,'Salta',  39,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1106,'Posadas',  40,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1107,'Resistencia',  41,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1108,'Corrientes',  42,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1109,'Santiago del Estero',  43,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1110,'San Salvador de Jujuy',  44,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1111,'San Juan',  45,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1112,'Viedma',  46,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1113,'Formosa',  47,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1114,'Neuquen',  48,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1115,'Rawson',  49,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1116,'San Luis',  50,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1117,'San Fernando del Valle de Catamarca',  51,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1118,'La Rioja',  52,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1119,'Santa Rosa',  53,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1120,'RIo Gallegos',  54,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1121,'Ushuaia',  55,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1122,'San Fernando de Apure',  56,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1123,'Maracay',  57,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1124,'Barinas',  58,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1125,'Ciudad BolIvar',  59,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1126,'Valencia',  60,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1127,'San Carlos',  61,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1128,'Tucupita',  62,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1129,'Los Roques',  63,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1130,'Caracas',  64,         0,         0,true,true,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1131,'Coro',  65,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1132,'San Juan De Los Morros',  66,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1133,'Barquisimeto',  67,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1134,'Merida',  68,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1135,'Los Teques',  69,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1136,'Maturin',  70,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1137,'La AsunciOn',  71,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1138,'Guanare',  72,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1139,'Cumana',  73,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1140,'San CristObal',  74,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1141,'Trujillo',  75,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1142,'La Guaira',  76,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1143,'San Felipe',  77,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1144,'Maracaibo',  78,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1145,'WhiteHorse',  79,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1146,'Saint Jhonn´s',  80,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1147,'Victoria',  81,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1148,'Edmonton',  82,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1149,'Regina',  83,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1150,'Winnipeg',  84,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1151,'Toronto',  85,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1152,'Quebec',  86,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1153,'Baker Lake',  87,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1154,'YellowKnife',  88,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1155,'Fredericton',  89,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1156,'Halifax',  90,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1157,'Charlottetown',  91,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1158,'Aguascalientes',  92,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1159,'Mexicali',  93,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1160,'La Paz',  94,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1161,'San Francisco de Campeche',  95,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1162,'Tuxtla Gutierrez',  96,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1163,'Chihuahua',  97,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1164,'Saltillo',  98,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1165,'Colima',  99,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1166,'Victoria de Durango', 100,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1167,'Guanajuato', 101,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1168,'Chilpancingo de los Bravo', 102,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1169,'Pachuca de Soto', 103,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1170,'Guadalajara', 104,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1171,'Toluca de Lerdo', 105,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1172,'Morelia', 106,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1173,'Cuernavaca', 107,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1174,'Tepic', 108,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1175,'Monterrey', 109,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1176,'Oaxaca de Juarez', 110,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1177,'Puebla de Zaragoza', 111,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1178,'Santiago de Queretaro', 112,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1179,'Chetumal', 113,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1180,'San Luis Potosi', 114,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1181,'Culiacan', 115,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1182,'Hermosillo', 116,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1183,'Villahermosa', 117,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1184,'Ciudad Victoria', 118,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1185,'Tlaxcala de Xicohtencatl', 119,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1186,'Xalapa-EnrIquez', 120,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1187,'Merida', 121,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1188,'Zacatecas', 122,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1189,'Ciudad de MExico', 123,         0,         0,true,true,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1190,'Rio Branco', 124,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1191,'Maceio', 125,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1192,'Macapa', 126,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1193,'Manaus', 127,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1194,'Salvador', 128,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1195,'Fortaleza', 129,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1196,'Brasilia', 130,         0,         0,true,true,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1197,'VitOria', 131,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1198,'Goiania', 132,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1199,'Sao LuIs', 133,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1200,'CuiabA', 134,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1201,'Campo Grande', 135,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1202,'Belo Horizonte', 136,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1203,'Belem', 137,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1204,'Joao Pessoa', 138,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1205,'Curitiba', 139,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1206,'Recife', 140,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1207,'Teresina', 141,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1208,'Rio de Janeiro', 142,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1209,'Natal', 143,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1210,'Porto Alegre', 144,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1211,'Porto Velho', 145,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1212,'Boa Vista', 146,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1213,'FlorianOpolis', 147,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1214,'Sao Paulo', 148,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1215,'Aracaju', 149,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1216,'Palmas', 150,         0,         0,true,false,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1218,'Montreal',  86,         0,         0,false,true,false);
INSERT INTO Ciudad (Id, Nombre, IdRegion, Area, Poblacion, CapitalRegion, CapitalPais, AreaMetropolitana) VALUES(1219,'Buenos Aires', 151,         0,         0,true,true,false);
